### ISSUE TITLE
文档问题

### ISSUE THREAD

**Issue by kiss291323003** [php-casbin/easyswoole-permission#2]
你好，我是easyswoole作者，非常感谢您适配了casbin这个优秀的库，不知道您是不是方便优化下文档，然后我在easyswoole文档那边，给您挂个demo或者是推荐链接过来。

**Comment by hsluoyz** [comment]
@kiss291323003 thanks for creating easyswoole!

Can you give more specific intructions for how to improve the docs? We have a README here already: https://github.com/php-casbin/easyswoole-permission

**Comment by hsluoyz** [comment]
@techoner @basakest

**Comment by hsluoyz** [comment]
@basakest any progress?

**Comment by hsluoyz** [comment]
@basakest the link is broken:

![image](https://user-images.githubusercontent.com/3787410/110939307-2d07e500-8370-11eb-830c-c82370958c9c.png)

![image](https://user-images.githubusercontent.com/3787410/110939347-38f3a700-8370-11eb-8716-34358d4e0553.png)

**Comment by basakest** [comment]
Oh, yes. I forget to spell the prefix php- before the keyword casbin. I will fix this problem as quickly as possible. The small image is broken because this project has not yet integrate any gitHub actions. Would it be better to remove it？

**Comment by hsluoyz** [comment]
@kiss291323003 see: https://github.com/php-casbin/easyswoole-permission/blob/master/README_CN.md

**Comment by hsluoyz** [comment]
@kiss291323003 hi, I think we have finished the CN docs: https://github.com/php-casbin/easyswoole-permission/blob/master/README_CN.md  can you put this middleware into easyswoole official site? Thanks!
